name: pathfinder_app
description: Pathfinder app (splash + login + OSM map)
publish_to: "none"

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  url_launcher: ^6.3.0
  # BUMPED: compatible with firebase_auth 6.x (uses web ^1.x)
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/SplashScreen.jpg

flutter_native_splash:
  color: "#C7F2E3"
  color_dark: "#C7F2E3"
  android_12:
    color: "#C7F2E3"
    color_dark: "#C7F2E3"
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/pathfinder_icon.png"
  adaptive_icon_foreground: "assets/images/pathfinder_icon.png"
  adaptive_icon_background: "#C7F2E3"
  remove_alpha_ios: true
